### ISSUE TITLE
How to add tag？

### ISSUE THREAD

**Issue by xiayuyu** [ridi/RxBus#10]
How do I add a tag to the send event？
Like this: RxBus.post("tag1", "1");

**Comment by freekering** [comment]
Hi.
Refer to [documentation](https://github.com/ridi/RxBus#defining-event-class), the event can be defined as a `class`.

If you need to deliver additional data through `RxBus`, you shall define some properties of that event class(The language is `Kotlin`).
```kotlin
class SomeEvent(val data1: String, val data2: Int)
```
And then, post the event included additional data you want.
```kotlin
RxBus.post(SomeEvent("a", 1)) // data1 = "a", data2 = 1
```

Thank you.
